schema_version: 1.0
session: redsun-mimir
frontend: pyqt

devices:
  serial:
    port: COM3
    baudrate: 115200
    device: COM3
  serial25:
    port: COM25
    baudrate: 9600
    device: COM25
  stage_xy: {}
  stage_z: {}
  spectra:
    port: serial25
  fw_controller:
    port: serial
  filterwheel:
    wheel_number: 0
    num_positions: 8
  camera: {}


presenters:
  storage_ctrl: {}
  acq_ctrl:
    callbacks: [det_ctrl, median_ctrl]
  median_ctrl: {}
  light_ctrl:
    timeout: 2.0
  motor_ctrl:
    timeout: 2.0
  det_ctrl:
    timeout: 2.0
  fw_ctrl:
    timeout: 2.0


views:
  light_widget: {}
  motor_widget: {}
  acq_widget: {}
  img_widget: {}
  det_widget: {}
  storage_widget: {}
  fw_widget: {}
